### 계좌 등록
POST http://localhost:8080/api/v1/banking/account/register
Content-Type: application/json

{
  "memberId": "2",
  "bankName": "hello Bank",
  "bankAccountNumber": 111111
}

### 계좌 등록
POST http://localhost:8080/api/v1/banking/account/register
Content-Type: application/json

{
"memberId": "2",
"bankName": "world Bank",
"bankAccountNumber": 222222
}

### 등록 계좌 조회
GET http://localhost:8080/api/v1/banking/account?memberId=2


### 펌뱅킹 요청
POST http://localhost:8080/api/v1/banking/firm-banking/request
Content-Type: application/json
X-MEMBER-ID: 2

{
  "fromBankName": "hello Bank",
  "fromBankAccountNumber": 111111,
  "toBankName": "world Bank",
  "toBankAccountNumber": 222222,
  "amount": 1000000
}

### 펌뱅킹 요청
POST http://localhost:8080/api/v1/banking/firm-banking/request
Content-Type: application/json
X-MEMBER-ID: 2

{
  "fromBankName": "hello Bank",
  "fromBankAccountNumber": 111111,
  "toBankName": "world Bank",
  "toBankAccountNumber": 222222,
  "amount": 3000000
}

### 펌뱅킹 요청 내역 조회
GET http://localhost:8080/api/v1/banking/firm-banking
X-MEMBER-ID: 2